---

- name: remove any previous golang directory
  ansible.builtin.file:
    path: "{{ golang.install_path }}"/go
    state: absent

- name: download golang archive
  get_url:
    url: {{golang.google_default_url}}/go{{ golang.version }}{{arch}}.tar.gz
    dest: /tmp/go{{ golang.version }}{{arch}}.tar.gz

- name: add path to OS profile
  ansible.builtin.lininfile:
    path: /etc/profile
    line: export PATH=$PATH:/usr/local/go/bin

- name: add path to user bash profile 
  ansible.builtin.lininfile:
    path: ~/.bashrc
    line: export PATH=$PATH:/usr/local/go/bin

- name: configure vim environment for golang dev
  ansible.builtin.git:
    repo: https://github.com/fatih/vim-go.git
    dest: ~/.vim/bundle/vim-go

